Repository nordicopen/easee_hass, pull requests merged in 2022-11, with the labels that each got.

#245 Remove unnecessesary call to get_site_state.
  custom_components/easee/controller.py
Labels: maintenance

#246 Load rc1 version of lib
  custom_components/easee/manifest.json
Labels: dependency

#248 Add new keys to manifest.json
  custom_components/easee/manifest.json
Labels: maintenance

#244 Always display currency symbol if set on site
  custom_components/easee/sensor.py
Labels: bugfix

#249 Improved handling of 400 and 403 responses
  custom_components/easee/controller.py
  custom_components/easee/manifest.json
  custom_components/easee/services.py
  custom_components/easee/switch.py
Labels: enhancement
