Repository nordicopen/easee_hass, pull requests merged in 2022-01, with the labels that each got.

#157 Fix for current limit compare not working
  custom_components/easee/controller.py
Labels: bugfix

#161 Change to EntityCategory
  custom_components/easee/const.py
Labels: bugfix

#163 Add support for diagnostics download
  custom_components/easee/diagnostics.py
Labels: enhancement

#164 Corrected initial selection of monitored sites
  custom_components/easee/config_flow.py
Labels: bugfix

#165 Bump dependency, version and lint
  Makefile
  custom_components/easee/const.py
  custom_components/easee/diagnostics.py
  custom_components/easee/manifest.json
  setup.cfg
Labels: chore, dependency
