Repository nordicopen/easee_hass, pull requests merged in 2022-10, with the labels that each got.

#220 Change to new entity naming model
  custom_components/easee/entity.py
Labels: maintenance

#221 Use _attr_* for static properties
  custom_components/easee/entity.py
Labels: maintenance

#223 UI-mode for services
  custom_components/easee/binary_sensor.py
  custom_components/easee/const.py
  custom_components/easee/entity.py
  custom_components/easee/sensor.py
  custom_components/easee/services.py
  custom_components/easee/services.yaml
  custom_components/easee/translations/en.json
Labels: enhancement

#225 Structure of schemas and misc small fixes
  custom_components/easee/services.py
  custom_components/easee/services.yaml
  custom_components/easee/translations/en.json
Labels: enhancement, maintenance

#219 Remove unecessary polling of schedules.
  custom_components/easee/controller.py
Labels: enhancement

#228 Schema structure in services
  custom_components/easee/services.py
  custom_components/easee/services.yaml
  custom_components/easee/translations/en.json
Labels: enhancement

#224 Create cost sensors for day, month and year.
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/entity.py
  custom_components/easee/manifest.json
Labels: enhancement

#235 Bump pyeasee lib to 0.7.46
  custom_components/easee/manifest.json
Labels: bugfix

#234 Add info about services and some minor adjustments
  INFO.md
  README.md
Labels: documentation, maintenance

#233 Update dev environment to align with HA
  requirements-dev.txt
  setup.cfg
Labels: maintenance

#230 Some changes to service descriptions in services.yaml + lint
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/entity.py
  custom_components/easee/services.py
  custom_components/easee/services.yaml
Labels: enhancement

#236 Bump version to 0.9.46 and lint
  Makefile
  custom_components/easee/config_flow.py
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/entity.py
  custom_components/easee/manifest.json
  custom_components/easee/sensor.py
  custom_components/easee/services.py
  setup.cfg
Labels: skip-changelog

#238 Use device class monetary for cost sensors
  custom_components/easee/const.py
  custom_components/easee/sensor.py
Labels: enhancement

#240 Large site fixes
  custom_components/easee/config_flow.py
  custom_components/easee/controller.py
Labels: bugfix
