Repository nordicopen/easee_hass, pull requests merged in 2023-05, with the labels that each got.

#321 Improve error handling around latest firmware API endpoint
  custom_components/easee/const.py
  custom_components/easee/controller.py
Labels: enhancement

#320 Fix URL to Easee portal
  custom_components/easee/entity.py
Labels: bugfix

#319 Add more status codes and translations
  .devcontainer/devcontainer.json
  .vscode/settings.json
  custom_components/easee/const.py
  custom_components/easee/translations/de.json
  custom_components/easee/translations/en.json
  custom_components/easee/translations/nb.json
  custom_components/easee/translations/nl.json
  custom_components/easee/translations/ro.json
  custom_components/easee/translations/sv.json
Labels: enhancement, translation

#318 Async improvements
  custom_components/easee/binary_sensor.py
  custom_components/easee/controller.py
  custom_components/easee/sensor.py
  custom_components/easee/switch.py
Labels: code quality

#322 Fix for KeyError in state function
  custom_components/easee/const.py
  custom_components/easee/entity.py
Labels: bugfix

#323 Removed schedule API polling
  custom_components/easee/const.py
  custom_components/easee/controller.py
Labels: maintenance

#313 Remove deprecated services
  custom_components/easee/services.py
  custom_components/easee/services.yaml
Labels: maintenance

#312 Address suggestions from pylint
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/entity.py
  custom_components/easee/services.py
Labels: code quality

#329 Fix for circuit_id not working as reference for service calls.
  custom_components/easee/services.py
Labels: bugfix

#324 More status codes - NL translation
  custom_components/easee/translations/nl.json
Labels: translation

#326 Show error message when no sites in account
  custom_components/easee/config_flow.py
  custom_components/easee/translations/de.json
  custom_components/easee/translations/en.json
  custom_components/easee/translations/nb.json
  custom_components/easee/translations/nl.json
  custom_components/easee/translations/ro.json
  custom_components/easee/translations/sv.json
Labels: enhancement, bugfix

#327 Added translation file for icelandic
  custom_components/easee/translations/is.json
Labels: translation

#332 Add missing translation keys to some lang files
  custom_components/easee/translations/de.json
  custom_components/easee/translations/is.json
  custom_components/easee/translations/nb.json
  custom_components/easee/translations/nl.json
  custom_components/easee/translations/ro.json
  custom_components/easee/translations/sv.json
  hacs.json
Labels: translation
