Repository nordicopen/easee_hass, pull requests merged in 2023-04, with the labels that each got.

#284 Use UnitOfPower etc instead of plain constants
  custom_components/easee/const.py
  custom_components/easee/entity.py
Labels: maintenance

#287 Change to new model for translations
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/entity.py
  custom_components/easee/translations/de.json
  custom_components/easee/translations/en.json
  custom_components/easee/translations/nb.json
  custom_components/easee/translations/ro.json
  custom_components/easee/translations/sensor.de.json
  custom_components/easee/translations/sensor.en.json
  custom_components/easee/translations/sensor.nb.json
  custom_components/easee/translations/sensor.ro.json
  custom_components/easee/translations/sensor.sv.json
  custom_components/easee/translations/sv.json
Labels: translation

#288 State polling with new API
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/manifest.json
Labels: enhancement, dependency

#286 Fix for latestFirmware change in cloud
  custom_components/easee/controller.py
Labels: bugfix

#289 Fix syntax in devcontainer.json and add i18n json editor
  .devcontainer/devcontainer.json
Labels: maintenance

#293 Enforce minimum HA version
  custom_components/easee/__init__.py
  custom_components/easee/const.py
Labels: enhancement

#291 Add translation of entity names and more
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/entity.py
  custom_components/easee/switch.py
  custom_components/easee/translations/de.json
  custom_components/easee/translations/en.json
  custom_components/easee/translations/nb.json
  custom_components/easee/translations/ro.json
  custom_components/easee/translations/sv.json
Labels: enhancement, translation

#294 Remove option to change units kW/W kWh/Wh
  custom_components/easee/__init__.py
  custom_components/easee/config_flow.py
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/entity.py
  custom_components/easee/translations/en.json
  custom_components/easee/translations/sv.json
Labels: enhancement

#302 Update nb.json
  custom_components/easee/translations/nb.json
Labels: translation

#305 Add Dutch translation
  custom_components/easee/translations/nl.json
Labels: translation

#306 Do not create circuit_current sensor for slave chargers
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/manifest.json
Labels: bugfix

#316 Firmware API not working anymore.
  custom_components/easee/controller.py
Labels: bug

#311 Entities return state as None instead of ""
  custom_components/easee/entity.py
Labels: bugfix
