Repository nordicopen/easee_hass, pull requests merged in 2023-09, with the labels that each got.

#351 New devcontainer
  .devcontainer.json
  .devcontainer/.gitignore
  .devcontainer/configuration.yaml
  .devcontainer/devcontainer.json
  .gitignore
  .pre-commit-config.yaml
  .ruff.toml
  .vscode/settings.json
  .vscode/tasks.json
  Makefile
  README.md
  requirements-devcontainer.txt
  requirements.txt
  scripts/dev-branch
  scripts/develop
  scripts/lint
  scripts/setup
  scripts/specific-version
  scripts/upgrade
Labels: maintenance, dev tools

#353 Fixes for product_code
  custom_components/easee/entity.py
  custom_components/easee/services.yaml
Labels: bugfix

#355 Fixing timezone issues
  custom_components/easee/services.py
Labels: bugfix

#356 Run ruff on all files
  custom_components/easee/__init__.py
  custom_components/easee/binary_sensor.py
  custom_components/easee/config_flow.py
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/sensor.py
  custom_components/easee/services.py
  custom_components/easee/switch.py
Labels: skip-changelog, code quality
