Repository nordicopen/easee_hass, pull requests merged in 2025-01, with the labels that each got.

#545 Changes to sensor configs
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/translations/en.json
Labels: enhancement, translation

#549 Add support for time to live for set_charger_dynamic_limit
  custom_components/easee/services.py
  custom_components/easee/services.yaml
  custom_components/easee/translations/en.json
Labels: enhancement, translation

#550 Represent LED strip brightness as a light entity
  .gitignore
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/entity.py
  custom_components/easee/light.py
  custom_components/easee/translations/en.json
  links.sh
Labels: enhancement, translation, dev tools

#552 Round brightness value to avoid truncation errors
  custom_components/easee/light.py
Labels: bugfix

#554 Update devcontainer to python 3.13
  .devcontainer.json
  .github/workflows/python-app.yml
  .pre-commit-config.yaml
  .ruff.toml
Labels: dev tools

#553 Guard brightness until value is populated
  custom_components/easee/light.py
Labels: bugfix

#555 Lokalise: Translations update
  custom_components/easee/translations/en.json
  custom_components/easee/translations/nb.json
  custom_components/easee/translations/sv.json
Labels: translation

#562 Fix deprecation warning
  custom_components/easee/config_flow.py
Labels: bugfix

#563 Switch to bumpver
  .github/release-drafter.yml
  .vscode/launch.json
  Makefile
  pyproject.toml
  requirements-dev.txt
  requirements-devcontainer.txt
  requirements.txt
Labels: dev tools

#565 Address suggestions from linters
  custom_components/easee/controller.py
Labels: code quality

#571 Update dev tools
  .github/release-drafter.yml
  .pylintrc
  .ruff.toml
  pyproject.toml
Labels: dev tools

#569 Cost refresh updated to comply with 10 calls per hour limit
  custom_components/easee/controller.py
Labels: bugfix, code quality

#570 Simplify observers handling in ProductData
  custom_components/easee/controller.py
Labels: code quality

#578 Fix for price/kWh sensor not updating on all chargers on a site.
  custom_components/easee/controller.py
  custom_components/easee/services.py
Labels: bugfix
