Repository nordicopen/easee_hass, pull requests merged in 2025-03, with the labels that each got.

#591 Lokalise: Translations update
  custom_components/easee/translations/fr.json
Labels: translation

#592 fix: Logger has no method print
  custom_components/easee/controller.py
Labels: bugfix

#593 Address some linter comments
  custom_components/easee/const.py
  custom_components/easee/controller.py
  custom_components/easee/device_condition.py
  custom_components/easee/diagnostics.py
  custom_components/easee/system_health.py
Labels: code quality
